version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: fundadream
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
  api:
    image: apifundadream
    depends_on:
      - mongodb
    build: 
      context: Backend
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000

  ui:
    image: uifundadream
    depends_on:
      - api
    build:
      context: Frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000

volumes:
  mongo_volume: